### ISSUE TITLE
Unsupported type for storing in int64 column

### ISSUE THREAD

**Issue by dipeshkd** [slingdata-io/sling-cli#22]
Hi 

I am trying to copy data from a MSSQL DB to S3 Bucket (as a PARQUET format).

I am getting to following error due to a specific column.

```
fatal:
~
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
~
~ execution failed
context canceled

~
context canceled

~ error writing row
unsupported type for storing in int64 column: int => 10

~ Could not FileSysWriteDataflow
context canceled

~
context canceled

~ error writing row
unsupported type for storing in int64 column: int => 10
```

This happens only on columns with datatype of smallint. 
When I cast this column as int the copy goes through

Copy to CSV format works fine

**Comment by flarco** [comment]
Thanks for reporting. I was able to reproduce.

I have released a new version (`1.0.40`) with code changes to fix this. Can you try it?

**Comment by dipeshkd** [comment]
Thanks for the quick response.

Unfortunately, I am still getting the same error after the upgrade.

**Comment by flarco** [comment]
Ah, really. Can you give more details? Like OS?
What SQL Server version are you using?
Can you give you the column types of the table you are extracting?

**Comment by dipeshkd** [comment]
Hi, sure, are the details. Let me know if you need any more information.

I am testing this on Windows 11. Also tested in Ubuntu (via WSL).

We have 3 DB instances with the same structure here are the versions. I have tested the same run in all 3 with the same issue
- Microsoft SQL Server 2012 (SP4) - This is where I tested first and came across the error.
- Microsoft SQL Server 2016 (SP3)
- Microsoft SQL Server 2019 (RTM-CU21)

The table I am testing with is small and has about 40 columns and 30 rows
The table has these datatypes:
- nchar
- nvarchar
- int
- smallint

Here is an example of the DDL for the table. I have reduced it to a few columns with the datatypes mentioned above. 

```sql
CREATE TABLE DB_test.dbo.table_1(
	column1 nchar(4) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
	column2 nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
	column3 smallint NULL,
	column4 int NULL,
	CONSTRAINT PK_COLUMN1 PRIMARY KEY (column1)
);
```

Tested this on another large table and it has the same issue with smallint
I have alot of tables that I would like to extract from all 3 dbs

**Comment by flarco** [comment]
@dipeshkd  can you run `sling update`, and try again with latest version?

**Comment by dipeshkd** [comment]
Hi @flarco, amazing. Its working great. Tested on all my sql server instances and also tested on one of my larger table
