### ISSUE TITLE
Redshift replication fails if source table is uppercased 

### ISSUE THREAD

**Issue by MiConnell** [slingdata-io/sling-cli#482]
## Issue Description

- Description of the issue: 

Running
`./sling run --src-conn MSSQL --src-stream dbo.TABLE_NAME --tgt-conn REDSHIFT_DEV --tgt-object public.{stream_table} --tgt-options '{"column_casing": "lower"}'`

as well as 
`./sling run --src-conn MSSQL --src-stream dbo.TABLE_NAME --tgt-conn REDSHIFT_DEV --tgt-object public.TABLE_NAME --tgt-options '{"column_casing": "lower"}'`

results in an error 
`did not find any columns for "public"."TABLE_NAME_tmp". Perhaps it does not exists, or user does not have read permission.`

- Sling version (`sling --version`): 
v1.2.14 is where this error is introduced, version 1.2.13 does not have this issue. (more details in the logs below)

- Operating System (`linux`, `mac`, `windows`): 
linux

- Replication Configuration: 
`./sling run --src-conn MSSQL --src-stream dbo.TABLE_NAME --tgt-conn REDSHIFT_DEV --tgt-object public.{stream_table} --tgt-options '{"column_casing": "lower"}'`

- Log Output (please run command with `-d`): 

## error log with 1.2.14:
```
2025-01-09 19:07:43 DBG Sling version: 1.2.14 (linux amd64)
2025-01-09 19:07:43 DBG type is db-db
2025-01-09 19:07:43 DBG using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2025-01-09 19:07:43 DBG using target options: {"datetime_format":"auto","file_max_rows":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"lower"}
2025-01-09 19:07:43 DBG opened "sqlserver" connection (conn-sqlserver-RyE)
2025-01-09 19:07:44 DBG opened "redshift" connection (conn-redshift-NGT)
2025-01-09 19:07:44 INF connecting to source database (sqlserver)
2025-01-09 19:07:44 INF connecting to target database (redshift)
2025-01-09 19:07:44 INF reading from source database
2025-01-09 19:07:44 DBG select * from "dbo"."TABLE_NAME"
2025-01-09 19:07:44 INF writing to target database [mode: full-refresh]
2025-01-09 19:07:44 DBG drop table if exists "public"."TABLE_NAME_tmp"
2025-01-09 19:07:44 DBG table "public"."TABLE_NAME_tmp" dropped
2025-01-09 19:07:44 DBG create table "public"."TABLE_NAME_tmp" (<column_names>)
2025-01-09 19:07:44 INF streaming data
2025-01-09 19:07:44 DBG opened "s3" connection (conn-s3-Esv)
2025-01-09 19:07:44 INF writing to s3 for redshift import
2025-01-09 19:07:44 DBG writing to s3://my-bucket/sling_temp/"public"."TABLE_NAME_tmp"/part.01 [fileRowLimit=0 fileBytesLimit=300000000 compression=gzip concurrency=4 useBufferedStream=false fileFormat=csv]
2025-01-09 19:07:44 DBG total written: 2.6 kB to s3://my-bucket/sling_temp/"public"."TABLE_NAME_tmp"
2025-01-09 19:07:44 DBG copying into redshift from s3
2025-01-09 19:07:44 DBG url: s3://my-bucket/sling_temp/"public"."TABLE_NAME_tmp"
2025-01-09 19:07:44 DBG COPY "public"."TABLE_NAME_tmp" (<column_names>)
FROM 's3://my-bucket/sling_temp/"public"."TABLE_NAME_tmp"'
credentials 'aws_access_key_id=***;aws_secret_access_key=***'
CSV delimiter ',' GZIP IGNOREHEADER 1 DATEFORMAT 'auto' TIMEFORMAT 'auto'
2025-01-09 19:07:45 DBG select count(*) cnt from "public"."TABLE_NAME_tmp"
2025-01-09 19:07:45 DBG drop table if exists "public"."TABLE_NAME"
2025-01-09 19:07:45 DBG table "public"."TABLE_NAME" dropped
2025-01-09 19:07:45 DBG create table "public"."TABLE_NAME" (<column_names>)
2025-01-09 19:07:45 INF created table "public"."TABLE_NAME"
2025-01-09 19:07:45 DBG drop table if exists "public"."TABLE_NAME_tmp"
2025-01-09 19:07:45 DBG table "public"."TABLE_NAME_tmp" dropped
2025-01-09 19:07:45 DBG closed "redshift" connection (conn-redshift-NGT)
2025-01-09 19:07:45 DBG closed "sqlserver" connection (conn-sqlserver-RyE)
2025-01-09 19:07:45 INF execution failed
fatal:
~ failure running task (see docs @ https://docs.slingdata.io/sling-cli)
--- task_run.go:99 func1 ---
--- task_run.go:553 runDbToDb ---
~ execution failed
--- task_run_write.go:479 WriteToDb ---
~ Could not WriteToDb
--- task_func.go:110 insertFromTemp ---
~ Could not insert from temp
--- database.go:1579 GetColumns ---
~ could not get column list for "public"."TABLE_NAME_tmp"
--- database.go:1502 GetTableColumns ---
did not find any columns for "public"."TABLE_NAME_tmp". Perhaps it does not exists, or user does not have read permission.
```

## no error log with v1.2.13
```

2025-01-09 19:07:29 DBG Sling version: 1.2.13 (linux amd64)
2025-01-09 19:07:29 DBG type is db-db
2025-01-09 19:07:29 DBG using source options: {"empty_as_null":false,"null_if":"NULL","datetime_format":"AUTO","max_decimals":-1}
2025-01-09 19:07:29 DBG using target options: {"datetime_format":"auto","file_max_rows":0,"max_decimals":-1,"use_bulk":true,"add_new_columns":true,"adjust_column_type":false,"column_casing":"lower"}
2025-01-09 19:07:30 INF connecting to source database (sqlserver)
2025-01-09 19:07:30 DBG opened "sqlserver" connection (conn-sqlserver-yzz)
2025-01-09 19:07:30 INF connecting to target database (redshift)
2025-01-09 19:07:30 DBG opened "redshift" connection (conn-redshift-SFu)
2025-01-09 19:07:30 INF reading from source database
2025-01-09 19:07:30 DBG select * from "dbo"."TABLE_NAME"
2025-01-09 19:07:30 INF writing to target database [mode: full-refresh]
2025-01-09 19:07:30 DBG drop table if exists "public"."table_name_tmp"
2025-01-09 19:07:30 DBG table "public"."table_name_tmp" dropped
2025-01-09 19:07:30 DBG create table "public"."table_name_tmp" ()
2025-01-09 19:07:30 INF streaming data
2025-01-09 19:07:30 DBG opened "s3" connection (conn-s3-rhe)
2025-01-09 19:07:30 INF writing to s3 for redshift import
2025-01-09 19:07:30 DBG writing to s3://my-bucket/temp/"public"."table_name_tmp"/part.01 [fileRowLimit=0 fileBytesLimit=300000000 compression=gzip concurrency=4 useBufferedStream=false fileFormat=csv]
2025-01-09 19:07:30 DBG total written: 2.6 kB to s3://my-bucket/temp/"public"."table_name_tmp"
2025-01-09 19:07:30 DBG copying into redshift from s3
2025-01-09 19:07:30 DBG url: s3://my-bucket/temp/"public"."table_name_tmp"
2025-01-09 19:07:30 DBG COPY "public"."table_name_tmp" (<column_names>)
FROM 's3://my-bucket/temp/"public"."table_name_tmp"'
credentials 'aws_access_key_id=***;aws_secret_access_key=***'
CSV delimiter ',' GZIP IGNOREHEADER 1 DATEFORMAT 'auto' TIMEFORMAT 'auto'
2025-01-09 19:07:31 DBG select count(*) cnt from "public"."table_name_tmp"
2025-01-09 19:07:31 DBG drop table if exists "public"."table_name"
2025-01-09 19:07:31 DBG table "public"."table_name" dropped
2025-01-09 19:07:31 DBG create table "public"."table_name" (<column_names>)
2025-01-09 19:07:31 INF created table "public"."table_name"
2025-01-09 19:07:31 DBG insert into "public"."table_name" (<column_names>) select <column_names> from "public"."table_name_tmp"
2025-01-09 19:07:31 DBG inserted rows into "public"."table_name" from temp table "public"."table_name_tmp"
2025-01-09 19:07:32 INF inserted 57 rows into "public"."table_name" in 2 secs [26 r/s] [8.0 kB]
2025-01-09 19:07:32 DBG drop table if exists "public"."table_name_tmp"
2025-01-09 19:07:32 DBG table "public"."table_name_tmp" dropped
2025-01-09 19:07:32 DBG closed "redshift" connection (conn-redshift-SFu)
2025-01-09 19:07:32 DBG closed "sqlserver" connection (conn-sqlserver-yzz)
2025-01-09 19:07:32 INF execution succeeded
```

Could it have something to do with this https://github.com/slingdata-io/sling-cli/commit/6002868 since this was the updated the table name formatting?

Though I have no problem running both of these select statements on my Redshift database, it still recognizes the table. 

```sql
-- table name is public.table_name
select * from public.TABLE_NAME;  -- ok

select * from public.table_name;  -- ok
```

**Comment by flarco** [comment]
Should be fixed in next release. You can try the [dev build](https://github.com/slingdata-io/sling-cli?tab=readme-ov-file#automated-dev-builds).

**Comment by ataft** [comment]
This issue still persists for me in sling 1.4.0. Here is my replication yaml:
```yaml
source: ORACLE
target: REDSHIFT_DEV

defaults:
  mode: full-refresh
  object: public.{stream_table}

streams:
  sysadm.ps_ssr_stdnt_grad:
```

And the output:
```log
sling run -r "replication.yaml"
12:10PM INF Sling CLI | https://slingdata.io
12:10PM INF Sling Replication | ORACLE -> REDSHIFT_DEV | sysadm.ps_ssr_stdnt_grad
12:10PM INF connecting to source database (oracle)
12:10PM INF connecting to target database (redshift)
12:10PM INF reading from source database
12:10PM INF writing to target database [mode: full-refresh]
12:10PM INF created table "public"."ps_ssr_stdnt_grad_tmp"
12:10PM INF streaming data
12:10PM INF writing to s3 for redshift import
40s 33,615 861 r/s 6.7 MB
12:11PM INF created table "public"."PS_SSR_STDNT_GRAD"
12:11PM INF execution failed
did not find any columns for "public"."PS_SSR_STDNT_GRAD". Perhaps it does not exists, or user does not have read permission.

fatal:
~ failure running replication (see docs @ https://docs.slingdata.io/sling-cli)
--------------------------- sysadm.ps_ssr_stdnt_grad ---------------------------
~ could not get column list for "public"."PS_SSR_STDNT_GRAD"
did not find any columns for "public"."PS_SSR_STDNT_GRAD". Perhaps it does not exists, or user does not have read permission.
```

I tried changing the streams to uppercase as well, which did not work. The only thing that works for me is explicitly naming the output for each stream table, e.g.
```yaml
source: ORACLE
target: REDSHIFT_DEV

defaults:
  mode: full-refresh

streams:
  sysadm.ps_ssr_stdnt_grad:
    object: public.ps_ssr_stdnt_grad
```

Perhaps a table_casing target option, similar to column_casing?

**Comment by flarco** [comment]
Ok, I added new runtime vars shown below, try the dev build,.

<img width="741" alt="Image" src="https://github.com/user-attachments/assets/ba51ee5e-3436-44f1-9c91-f68606b5cadd" />

**Comment by ataft** [comment]
Tested with Sling v1.4.1 and it works. Thank you!
